### ISSUE TITLE
Bug with table parsing

### ISSUE THREAD

**Issue by assusdan** [Creeplays/LK.BIN-Parser#3]
I got this table: https://gist.github.com/assusdan/a7314968ec9b4cd68841a5fcab91cd70
when it must finish at line 200 : https://gist.github.com/assusdan/a7314968ec9b4cd68841a5fcab91cd70#file-gistfile1-txt-L200
My lk.bin: https://cloud.mail.ru/public/7SPz/eH4whBYuE

**Comment by CertainLach** [comment]
Fixed in 8cefdbc3c6e71eea3ec83f66b7a48452fc7106ee
